### ISSUE TITLE
When the module folder is not based on Template Folder they will not get taken into account

### ISSUE THREAD

**Issue by avwolferen** [zkniebel/SitecoreDXG#53]
When a foundation/feature/project module folder is not based on the Template Folder but on the  common folder (/sitecore/templates/Common/Folder) those templates will not end up in the template architecture.

When you have features that have dependencies (base template) in foundation templates that are located inside a non Template Folder based item the generator crashes.

**Comment by zkniebel** [comment]
Technically, this is a bug in the SitecoreUML Service for Sitecore. I will fix the bug and update this thread.

**Comment by avwolferen** [comment]
Line 50 in the SitecoreDataManager ;)

**Comment by avwolferen** [comment]
Awesome! I expect it to be in the SitecoreDataManager -> GetTemplateArchitectureForExport()

**Comment by zkniebel** [comment]
Exactly right. The fix has been deployed in [SitecoreUML 1.3.8](https://github.com/zkniebel/SitecoreUML/releases/tag/1.3.8) and you can see the code changes for this fix in [this commit](https://github.com/zkniebel/SitecoreUML/commit/4f8f31ca70201bbe4ed694b847bf0357bc31da5d#diff-2bfcab1b80b7ad379f044ee92865d11e).
